config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "/profile", to: "pages#profile"
  # definir o que tera na home (opcao para o index dos livros, para publicar um livro etc)

  resources :books do
    resources :trades, only: [:new, :create]
    patch :change_availability_to_true, on: :member
    resources :reviews, only: :create
  end

  resources :trades, only: [:destroy, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :reviews, dependent: :destroy
  has_one_attached :photo

  validates :title, :author, :year, :genre, presence: true
  validates :year, numericality: { only_integer: true }
  validates :genre, inclusion: %w[fantasy dystopian adventure romance horror thriller children]
  # TODO: Upload image for a book

  include PgSearch::Model
  pg_search_scope :search_by_attributes,
    against: [ :title, :author, :genre, :year ],
    using: { tsearch: { prefix: true } }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :book
  belongs_to :user

  validates :content, presence: true
  validates :rating, numericality: { only_integer: true }, inclusion: { in: 0..5 }
end

app/models/trade.rb
class Trade < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # validates :name, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  has_many :books, dependent: :destroy
  has_many :trades
  has_many :reviews, dependent: :destroy

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :find_book, except: %i[index new create]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    if params[:query].present?
      @books = Book.search_by_attributes(params[:query])
                   .where(available: true)
                   .where.not(user: current_user)
    else
      @books = Book.where(available: true)
                   .where.not(user: current_user)
    end
  end

  def show
    @trade = Trade.new
    @review = Review.new(book: @book)

    @markers = [{
      lat: @book.user.latitude,
      lng: @book.user.longitude
    }]
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user = current_user
    if @book.save!
      redirect_to book_path(@book)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    find_book
  end

  def update
    @book.update(book_params)
    if @book.save
      redirect_to book_path(@book)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @book.destroy
    redirect_to books_path, status: :see_other
  end

  def change_availability_to_true
    @book.available = true
    @book.save!
    redirect_to profile_path
  end

  private

  def find_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :author, :year, :genre, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    # TODO: Popular book suggestions by reviews
    @books = Book.last(4).reverse
  end

  def profile
    @trades = current_user.trades
    @available_books = current_user.books.where(available: true)
    @unavailable_books = current_user.books.where(available: false)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.new(review_params)
    @book = Book.find(params[:book_id])
    @review.book = @book
    @review.user = current_user
    if @review.save
      redirect_to book_path(@book)
    else
      flash[:alert] = "Something went wrong."
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/controllers/trades_controller.rb
class TradesController < ApplicationController

  def index
    @trades = Trade.where(user_id: current_user.id)
  end

  def create
    @book = Book.find(params[:book_id])
    @trade = Trade.new(trades_params)
    @trade.book = @book
    @trade.user = current_user
    if @trade.save
      @book.available = false
      @book.save!
      redirect_to book_path(@book)
      # ou redirecionar para o index de trades deste usuario
    else
      render "books/show", status: :unprocessable_entity
    end
  end

  def destroy
    @trade = Trade.find(params[:id])
    @trade.destroy
    redirect_to books_path, status: :see_other
  end

  private

  def trades_params
    params.require(:trade).permit(:return_date, :trade_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_book.html.erb
<div class="col-xl-3 col-lg-4 col-md-6 mb-3">
  <div class="card h-100 shadow-sm border-0 rounded-0 bg-light">
    <% if book.photo.attached? %>
      <%= cl_image_tag book.photo.key, class: "book card-img-top", crop: :fill %>
    <% else %>
      <%= image_tag "livro.jpeg", class: "book card-img-top" %>
    <% end %>

    <div class="card-body">
      <span class="badge rounded-pill text-bg-success text-white position-absolute" style="top: 15px"><%= book.genre.capitalize %></span>
      <h5 class="card-title fw-bold"><%= book.title %> <small class="fw-lighter fs-6 text-muted">(<%= book.year %>)</small></h5>
      <p class="card-subtitle mb-2">Author: <%= book.author %></p>
    </div>
    <div class="card-footer bg-light text-center">
      <%= link_to book_path(book), class: "btn btn-outline-danger rounded-0 d-block w-100 stretched-link mb-2" do %>
        <i class="fa-solid fa-plus me-2"></i>
        Book details
      <% end %>
      <small class="card-text text-muted">Offered by: <%= book.user.name %></small>
    </div>
  </div>
</div>

app/views/books/_form.html.erb
<%= simple_form_for @book do |f| %>
  <%= f.input :title %>
  <%= f.input :author %>
  <%= f.input :year %>
  <%= f.input :genre, collection: %w[fantasy dystopian adventure romance horror thriller children] %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "Submit", class: "btn btn-dark w-100 d-block" %>
<% end %>

app/views/books/_trade_form.html.erb
       <div class="card bg-light border-0 rounded-0 shadow-sm">
            <div class="card-body">
              <h5 class="card-title">Would you like to borrow it?</h5>
              <%= simple_form_for [@book, @trade], data: {turbo: false} do |f| %>
                <%= f.input :trade_date, as: :date %>
                <%= f.input :return_date, as: :date %>
                <%= f.button :submit, class: "btn btn-warning d-block w-100" %>
              <% end %>
            </div>
          </div>

app/views/books/edit.html.erb
<div class="container mt-5 px-5">
  <div class="row justify-content-center align-items-center">
    <h1>Edit your book offer</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/books/index.html.erb
<div class="container my-5">
  <h1 class="mb-3"><span><%= @books.count %></span> Book<%= "s" if @books.count >= 1 %> ready to be borrowed</h1>
  <div class="row justify-content-center">
    <% @books.each do |book| %>
      <%= render 'book', book: book %>
    <% end %>
  </div>
</div>



<%#= cl_image_tag("THE_IMAGE_ID_FROM_LIBRARY", width: 400, height: 300, crop: :fill) %>

app/views/books/new.html.erb
<div class="container mt-5 px-5">
  <div class="row justify-content-center align-items-center">
    <h1>Offer a book</h1>
    <%= render "form" %>
  </div>
</div>

app/views/books/show.html.erb
<div class="container my-5">
  <%= link_to books_path, class: "text-decoration-none text-muted" do %>
    <i class="fa-solid fa-arrow-left-long"></i>
    Return
  <% end %>

  <div class="row justify-content-center mb-3">
    <div class="col-md-4">
      <% if @book.photo.attached? %>
        <%= cl_image_tag @book.photo.key, class: "book card-img-top", crop: :fill %>
      <% else %>
        <%= image_tag "livro.jpeg", class: "book card-img-top" %>
      <% end %>
      <% if current_user && current_user.name == @book.user.name %>

        <p class="d-block text-muted text-center">This book belongs to <span class="fw-bold">you</span></p>
      <% else %>
        <p class="d-block text-muted text-center">This book belongs to <span class="fw-bold"><%= @book.user.name %></span></p>
      <% end %>
    </div>
    <div class="col-md-5 mb-5 mb-md-0">
      <span class="badge rounded-pill text-bg-success text-white"><%= @book.genre.capitalize %></span>
      <h1><%= @book.title %>
        <span class="fs-5">(<%= @book.year %>)<span>
      </h1>
      <p class="mb-4">By
        <span class="fw-bold"><%= @book.author.capitalize %></span>
      </p>

      <% if current_user == @book.user %>
        <%= link_to edit_book_path(@book), class: "btn btn-outline-secondary me-2" do %>
          <i class="fa-solid fa-pen-to-square"></i>
          Edit offer
        <% end %>
        <%= link_to profile_path, class: "btn btn-outline-danger me-2", data: {turbo_method: :delete, turbo_confirm: "Are you sure?" } do %>
          <i class="fa-solid fa-trash-can"></i>
          Delete offer
        <% end %>
        <br>
        <% unless @book.available? %>
          <%= link_to change_availability_to_true_book_path(@book), class: "btn btn-outline-success mt-3", data: {turbo_method: :patch } do %>
            <i class="fa-regular fa-circle-check"></i>
            Make available
          <% end %>
        <% end %>
      <% else %>
        <% if @book.available %>
          <%= render 'trade_form' %>
        <% end %>
      <% end %>
    </div>
    <div class="col-md-9 mb-3">
      <h5>This book is here:</h5>
      <div class="mx-auto" style="width: 100%; height: 300px;" data-controller="map" data-map-markers-value="<%= @markers.to_json %>" data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
    </div>
    <div class="col-md-9">
      <div class="row justify-content-center">
        <div class="col-lg-8 col-md-6">
          <h5>Reviews</h5>
          <% if @book.reviews.count == 0 %>
            <p>No reviews yet. Be the first to leave a review?</p>
          <% end %>
          <% @book.reviews.each do |review| %>
            <div class="card w-100 mb-2 border-0 rounded-0 shadow-sm">
              <div class="card-body py-2">
                <p class="card-title fw-bold"><%= review.user.name %>
                  <% review.rating.times do %>
                    <i class="fa-solid fa-star text-info"></i>
                  <% end %>
                  <% (5 - review.rating).times do %>
                    <i class="fa-regular fa-star text-info"></i>
                  <% end %>
                </p>
                <p class="card-text"><%= review.content %></p>
              </div>
            </div>
          <% end %>
        </div>
        <div class="col-lg-4 col-md-6">
          <h5>Leave a review</h5>
          <%= simple_form_for [@book, @review] do |f| %>
            <%= f.input :rating, collection: (1..5).to_a, label: "Rate the book", input_html: {data: {controller: "star-rating"}} %>
            <%= f.input :content %>
            <%= f.submit "Submit", class: "btn btn-dark w-100 d-block" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TakeMyBook</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=DM+Serif+Display&family=Oxygen:wght@400;700&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <link href="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.js"></script>
  </head>

  <body>
    <%= render "shared/flashes" %>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/pages/_book-sm.html.erb
<div class="col-lg-4 col-md-6 mb-3">
  <div class="card h-100 shadow-sm border-0 rounded-0 bg-light">
    <% if book.photo.attached? %>
      <%= cl_image_tag book.photo.key, class: "book card-img-top", crop: :fill %>
    <% else %>
      <%= image_tag "livro.jpeg", class: "book card-img-top" %>
    <% end %>

    <div class="card-body">
      <span class="badge rounded-pill text-bg-success text-white position-absolute" style="top: 15px"><%= book.genre.capitalize %></span>
      <h5 class="card-title fw-bold"><%= book.title %> <small class="fw-lighter fs-6 text-muted">(<%= book.year %>)</small></h5>
      <p class="card-subtitle mb-2">Author: <%= book.author %></p>
    </div>
    <div class="card-footer bg-light text-center">
      <%= link_to book_path(book), class: "btn btn-outline-danger rounded-0 d-block w-100 stretched-link mb-2" do %>
        <i class="fa-solid fa-plus me-2"></i>
        Book details
      <% end %>
      <small class="card-text text-muted">Offered by: <%= book.user.name %></small>
    </div>
  </div>
</div>

app/views/pages/_trade.html.erb
<div class="col-lg-4 col-md-6 mb-3">
  <div class="card border-0 shadow-sm h-100 rounded-0">
    <% if trade.book.photo.attached? %>
      <%= cl_image_tag trade.book.photo.key, class: "book card-img-top", crop: :fill %>
    <% else %>
      <%= image_tag "livro.jpeg", class: "book card-img-top" %>
    <% end %>
    <div class="card-body">
      <h5 class="card-title fw-bold"><%= trade.book.title %> <small class="fw-lighter fs-6 text-muted">(<%= trade.book.year %>)</small></h5>
      <p class="card-subtitle mb-2">By <%= trade.book.author %></p>
      <p class="card-text"><span class="fw-bold text-muted">Borrowed on: </span><%= trade.trade_date.strftime("%d %b %Y") %></p>
      <p class="card-text"><span class="fw-bold text-muted">Return by: </span><%= trade.return_date.strftime("%d %b %Y") %></p>
    </div>
    <div class="card-footer text-center">
      <small class="card-text text-muted">Offered by: <%= trade.book.user.name %></small>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner-home p-5 mb-4">
  <div class="container-fluid text-center text-white py-5">
    <h1 class="display-5 fw-bold">Take My Book</h1>
    <p class="col-md-8 fs-4 w-100">A marketplace for trading and lending books.<br>How would you like to start?</p>
    <%= link_to "Borrow a book", books_path, class: "btn btn-danger rounded-0 text-light me-2" %>
    <%= link_to "Lend a book", new_book_path, class: "btn btn-outline-light rounded-0" %>
  </div>
</div>
<div class="container my-4">
  <div class="row">
    <div class="col-12">
      <h2 class="mb-4 border-bottom border-secondary">Newest books</h2>
    </div>
    <% @books.each do |book| %>
      <%= render "books/book", book: book %>
    <% end %>
  </div>
</div>

app/views/pages/profile.html.erb
<div class="container my-5">

  <h1 class="d-inline mb-3"><%= current_user.name %>'s Profile</h1>
  <span class="text-muted fs-6 ms-2">Not you? <%= link_to "Sign out", destroy_user_session_path, class: "text-danger" %></span>
  <div class="row g-0 justify-content-center mt-3">

    <div class="col-lg-3 bg-white border-end">
      <div class="card border-0">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            <h5 class="card-title">Account Details</h5>
            <p class="card-text text-muted">
              <span class="fw-bold">Name: </span>
              <%= current_user.name %>
            </p>
            <p class="card-text text-muted">
              <span class="fw-bold">Email: </span>
              <%= current_user.email %>
            </p>
            <p class="card-text text-muted">
              <span class="fw-bold">Address: </span>
              <%= current_user.address %>
            </p>
            <%= link_to "Edit account", edit_user_registration_path, class: "btn btn-outline-danger d-block w-100" %>
          </li>
          <li class="list-group-item">
            <h5 class="card-title">Account Stats</h5>
            <p class="card-text text-muted">
              <span class="fw-bold">User since: </span>
              <%= current_user.created_at.strftime("%d %b %Y") %>
            </p>
            <p class="card-text text-muted">
              <span class="fw-bold">Books offered: </span>
              <%= current_user.books.count %>
            </p>
            <p class="card-text text-muted">
              <span class="fw-bold">Number of trades: </span>
              <%= @trades.count %>
            </p>
          </li>
          <li class="list-group-item">
            <%= link_to "Delete my account", user_registration_path, data: { turbo_confirm: "Are you sure?", turbo_method: :delete }, class: "btn btn-outline-danger d-block w-100" %>
          </li>
        </ul>
      </div>
    </div>

    <div class="col-lg-9 p-3 bg-white">
      <h3 class="mb-3">Your trades</h3>
      <% if @trades.count == 0 %>
        <p>No trades yet</p>
      <% else %>
        <div class="row justify-content-center mb-5">
          <% @trades.each do |trade| %>
            <%= render "trade", trade: trade %>
          <% end %>
        </div>
      <% end %>

      <h3 class="mb-3">Your books
        <% if current_user.books.count > 0 %>
          <%= link_to "Offer another book", new_book_path, class: "btn btn-link text-warning" %>
        <% end %>
      </h3>
      <% if current_user.books.count == 0 %>
        <p>No books offered yet
          <%= link_to "Offer a book", new_book_path, class: "btn btn-link text-warning" %>
        </p>
      <% else %>
        <div class="row justify-content-center">
          <h4>Unavailable books:</h4>
          <% if @unavailable_books.count == 0 %>
            <p>No books were found</p>
          <% else %>
            <% @unavailable_books.each do |book| %>
            <%= render 'book-sm', book: book %>
            <% end %>
          <% end %>
        </div>
        <div class="row justify-content-center">
          <h4>Available books:</h4>
          <% if @available_books.count == 0 %>
            <p>No books were found</p>
          <% else %>
            <% @available_books.each do |book| %>
            <%= render 'book-sm', book: book %>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm bg-dark navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand", style: "flex-grow: 2;" do %>
      <h2 class="text-white">
        <span class="text-muted"><i class="fa-solid fa-book-open me-2"></i>Take my</span>
        Book
      </h2>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent" style="flex-grow: 2;">
      <ul class="navbar-nav align-items-center justify-content-between w-100">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= form_with url: books_path, method: :get, class: "input-group" do %>
              <%= text_field_tag :query, params[:query], class: "form-control border-0", placeholder: "Find a book" %>
              <%= button_tag class: "btn btn-secondary rounded-0" do %>
                <i class="fa-solid fa-magnifying-glass"></i>
              <% end %>
            <% end %>
          </li>
          <li class="nav-item dropdown">
            <%# <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <a class="nav-link dropdown-toggle pe-auto text-light" style="cursor: pointer;" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >
              Welcome, <span class="fw-bold"><%= current_user.name %></span>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My profile", profile_path, class: "dropdown-item" %>
              <%= link_to "Add a new book", new_book_path, class: "dropdown-item" %>
              <%= link_to destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item text-danger" do %>
                <i class="fa-solid fa-arrow-right-from-bracket"></i>
                Log out
              <% end %>
            </div>
          </li>
        <% else %>
          <li class="nav-item ms-auto">
            <%= link_to "Login", new_user_session_path, class: "nav-link btn btn-danger text-light rounded-0 me-3 px-3" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link text-light text-decoration-underline" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/trades/index.html.erb
<h1>index de trades</h1>

app/views/trades/new.html.erb
<h1>new de trade</h1>
<%= simple_form_for [@book, @trade] do |f| %>
  <%= f.input :trade_date %>
  <%= f.input :return_date %>
  <%= f.button :submit %>
<% end %>